source 'https://rubygems.org'

gem 'fastlane', '~> 2.221'
gem 'cocoapods', '~> 1.16'
gem 'xcpretty', '~> 0.3'

# Fastlane plugins
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)